### ISSUE TITLE
Is the UserClient still working?

### ISSUE THREAD

**Issue by yuanxintaxon** [maxpowel/crypto_com_client#4] opened 2022-04-03 11:02 UTC
i'm getting unauthorized even if i entered the correct API key and secret key. 

{'id': 1, 'method': 'private/get-order-history', 'code': 10002, 'message': 'UNAUTHORIZED', ...}

**Comment by crgimenes** [comment] 2022-06-20 17:32
I'm having the same problem here, I always get *unauthorized*.
Any idea?

**Comment by crgimenes** [comment] 2022-06-20 19:51
it seems that the Rust version is working but I still can't figure out what's different. https://github.com/maxpowel/rs-crypto-com-exchange

**Comment by factec-kyle** [comment] 2024-02-07 07:21
Did you call client.authenticate() before send private message?
Example on the README.md omitted this
```
await client.authenticate()
event = await client.next_event()
print(event)
```

**Comment by maxpowel** [comment] 2024-02-08 09:40
Hi guys, the exchange changed a little bit how the private api works. It should be fixed now.
I also added an example for get-order-history to ensure your use case is fixed

More info here https://github.com/maxpowel/crypto_com_client/pull/6/files

The version 1.2 contains the fix, please tell me if the issue is fixed for you.

**Comment by maxpowel** [comment] 2024-02-08 09:42
> Did you call client.authenticate() before send private message? Example on the README.md omitted this
> 
> ```
> await client.authenticate()
> event = await client.next_event()
> print(event)
> ```

You are right, I have just updated the README.md

**Closed as completed** 2024-04-04 17:31 UTC
